// ─── Link Generator (/genlink, /batch, channel_post handler) ───

import type { BotContext } from '../../types';
import { encode } from '../../utils/base64';
import { isAdmin } from '../middleware/auth';
import { logger } from '../../utils/logger';

const MIGRATOR_BOT = 'LelouchAMbot';

// ─── Extract channel_id + message_id from forwarded message or text link ───

function extractMessageInfo(ctx: BotContext, msg: any): { channelId: number; msgId: number } | null {
  // Priority 1: Legacy forward fields
  if (msg.forward_from_chat) {
    const chatId = msg.forward_from_chat.id;
    const msgId = msg.forward_from_message_id;
    if (chatId && ctx.settings.all_db_ids.includes(chatId)) {
      return { channelId: chatId, msgId };
    }
  }

  // Priority 2: Modern forward_origin
  if (msg.forward_origin?.type === 'channel' && msg.forward_origin.chat) {
    const chatId = msg.forward_origin.chat.id;
    const msgId = msg.forward_origin.message_id;
    if (chatId && ctx.settings.all_db_ids.includes(chatId)) {
      return { channelId: chatId, msgId };
    }
  }

  // Priority 3: Text link
  if (msg.text) {
    const pattern = /https:\/\/t\.me\/(?:c\/)?(.*?)\/(\d+)/;
    const match = msg.text.match(pattern);
    if (match) {
      const channelStr = match[1];
      const msgId = parseInt(match[2], 10);
      for (const dbId of ctx.settings.all_db_ids) {
        if (String(dbId) === `-100${channelStr}`) {
          return { channelId: dbId, msgId };
        }
      }
    }
  }

  return null;
}

// ─── /genlink command ───

export async function handleGenlink(ctx: BotContext) {
  const msg = ctx.update.message!;

  // Check if the message itself is a forward or contains a link
  const info = extractMessageInfo(ctx, msg);
  if (!info) {
    await ctx.api.sendMessage(msg.chat.id,
      '<b>📨 Forward a message from DB Channel or send its link</b>\n\n<i>The message must be from a configured DB channel.</i>',
      { parse_mode: 'HTML' }
    );
    return;
  }

  const base64String = encode(`single_${info.channelId}_${info.msgId}`);
  const migratorLink = `https://t.me/${MIGRATOR_BOT}?start=${base64String}`;
  const directLink = `https://t.me/${ctx.settings.bot_username}?start=${base64String}`;

  const responseText = `<b>✅ Single File ʟɪɴᴋ ɢᴇɴᴇʀᴀᴛᴇᴅ!</b>\n\n<b>📤 ꜰᴏʀ ᴘᴜʙʟɪᴄ ᴄʜᴀɴɴᴇʟꜱ (ᴜꜱᴇ ᴛʜɪꜱ!):</b>\n<code>${migratorLink}</code>\n\n<blockquote><b>🔗 ᴀʟᴛᴇʀɴᴀᴛɪᴠᴇ ʟɪɴᴋ:</b>\n<code>${directLink}</code></blockquote>`;

  await ctx.api.sendMessage(msg.chat.id, responseText, {
    parse_mode: 'HTML',
    disable_web_page_preview: true,
    reply_markup: { inline_keyboard: [
      [{ text: 'ʀᴇᴅɪʀᴇᴄᴛ ʙᴏᴛ ʟɪɴᴋ', url: migratorLink }],
      [{ text: 'ᴄᴜʀʀᴇɴᴛ ʙᴏᴛ ʟɪɴᴋ', url: directLink }],
    ]},
  });

  logger.info('linkGen', `Single link generated by ${msg.from!.id}: ${info.msgId} from ${info.channelId}`);
}

// ─── /batch command (expects two forwarded messages or text) ───

export async function handleBatch(ctx: BotContext) {
  const msg = ctx.update.message!;
  const text = msg.text || '';
  const parts = text.split(/\s+/);

  // If command has args: /batch channel_id start_id end_id
  if (parts.length >= 4) {
    const channelId = parseInt(parts[1], 10);
    const startId = parseInt(parts[2], 10);
    const endId = parseInt(parts[3], 10);

    if (isNaN(channelId) || isNaN(startId) || isNaN(endId)) {
      await ctx.api.sendMessage(msg.chat.id, '<b>Usage:</b> <code>/batch channel_id first_msg_id last_msg_id</code>', { parse_mode: 'HTML' });
      return;
    }

    const base64String = encode(`batch_${channelId}_${startId}_${endId}`);
    const migratorLink = `https://t.me/${MIGRATOR_BOT}?start=${base64String}`;
    const directLink = `https://t.me/${ctx.settings.bot_username}?start=${base64String}`;

    await ctx.api.sendMessage(msg.chat.id,
      `<b>✅ Batch ʟɪɴᴋ ɢᴇɴᴇʀᴀᴛᴇᴅ!</b>\n\n<b>📤 ꜰᴏʀ ᴘᴜʙʟɪᴄ ᴄʜᴀɴɴᴇʟꜱ:</b>\n<code>${migratorLink}</code>\n\n<blockquote><b>🔗 ᴀʟᴛᴇʀɴᴀᴛɪᴠᴇ:</b>\n<code>${directLink}</code></blockquote>`,
      {
        parse_mode: 'HTML',
        disable_web_page_preview: true,
        reply_markup: { inline_keyboard: [
          [{ text: 'ʀᴇᴅɪʀᴇᴄᴛ ʙᴏᴛ ʟɪɴᴋ', url: migratorLink }],
          [{ text: 'ᴄᴜʀʀᴇɴᴛ ʙᴏᴛ ʟɪɴᴋ', url: directLink }],
        ]},
      }
    );

    logger.info('linkGen', `Batch link generated: ${startId}-${endId} from ${channelId}`);
    return;
  }

  // If just /batch with no args, set pending action for two-step flow
  await ctx.db.setPendingAction(msg.from!.id, 'batch_first');
  await ctx.api.sendMessage(msg.chat.id,
    '<b>📨 Forward the <u>First Message</u> from DB Channel</b>\n\n<i>You can also send the message link, or use:</i>\n<code>/batch channel_id first_msg_id last_msg_id</code>',
    { parse_mode: 'HTML' }
  );
}

export async function processBatchFirst(ctx: BotContext) {
  const msg = ctx.update.message!;
  const info = extractMessageInfo(ctx, msg);
  if (!info) {
    await ctx.api.sendMessage(msg.chat.id, '❌ <b>Invalid Message</b>\n\nNot from a configured DB Channel.', { parse_mode: 'HTML' });
    return;
  }

  await ctx.db.setPendingAction(msg.from!.id, 'batch_second', { channelId: info.channelId, firstMsgId: info.msgId });
  await ctx.api.sendMessage(msg.chat.id,
    '<b>📨 Forward the <u>Last Message</u> from DB Channel</b>\n\n<i>You can also send the message link</i>',
    { parse_mode: 'HTML' }
  );
}

export async function processBatchSecond(ctx: BotContext, data: any) {
  const msg = ctx.update.message!;
  const info = extractMessageInfo(ctx, msg);
  if (!info) {
    await ctx.api.sendMessage(msg.chat.id, '❌ <b>Invalid Message</b>\n\nNot from a configured DB Channel.', { parse_mode: 'HTML' });
    return;
  }

  if (info.channelId !== data.channelId) {
    await ctx.api.sendMessage(msg.chat.id, '❌ <b>Error</b>\n\nBoth messages must be from the same channel.', { parse_mode: 'HTML' });
    return;
  }

  const base64String = encode(`batch_${data.channelId}_${data.firstMsgId}_${info.msgId}`);
  const migratorLink = `https://t.me/${MIGRATOR_BOT}?start=${base64String}`;
  const directLink = `https://t.me/${ctx.settings.bot_username}?start=${base64String}`;

  await ctx.api.sendMessage(msg.chat.id,
    `<b>✅ Batch ʟɪɴᴋ ɢᴇɴᴇʀᴀᴛᴇᴅ!</b>\n\n<b>📤 ꜰᴏʀ ᴘᴜʙʟɪᴄ ᴄʜᴀɴɴᴇʟꜱ:</b>\n<code>${migratorLink}</code>\n\n<blockquote><b>🔗 ᴀʟᴛᴇʀɴᴀᴛɪᴠᴇ:</b>\n<code>${directLink}</code></blockquote>`,
    {
      parse_mode: 'HTML',
      disable_web_page_preview: true,
      reply_markup: { inline_keyboard: [
        [{ text: 'ʀᴇᴅɪʀᴇᴄᴛ ʙᴏᴛ ʟɪɴᴋ', url: migratorLink }],
        [{ text: 'ᴄᴜʀʀᴇɴᴛ ʙᴏᴛ ʟɪɴᴋ', url: directLink }],
      ]},
    }
  );
}

// ─── Channel Post Handler (admin uploads file → DB channel) ───

export async function handleChannelPost(ctx: BotContext) {
  const msg = ctx.update.message!;
  const db = ctx.settings.databases.primary;
  if (!db) {
    await ctx.api.sendMessage(msg.chat.id, '❌ <b>No database configured.</b>', { parse_mode: 'HTML' });
    return;
  }

  const replyMsg = await ctx.api.sendMessage(msg.chat.id, '⏳ <b>Processing file...</b>', { parse_mode: 'HTML' });

  try {
    const postResult = await ctx.api.copyMessage(db, msg.chat.id, msg.message_id, { disable_notification: true });
    const postMsgId = postResult.message_id;

    const base64String = encode(`single_${db}_${postMsgId}`);
    const migratorLink = `https://t.me/${MIGRATOR_BOT}?start=${base64String}`;
    const currentBotLink = `https://t.me/${ctx.settings.bot_username}?start=${base64String}`;

    const responseText = `<b>✅ ꜰɪʟᴇ ᴜᴘʟᴏᴀᴅᴇᴅ ꜱᴜᴄᴄᴇꜱꜱꜰᴜʟʟʏ!</b>\n\n<b>📤 ꜰᴏʀ ᴘᴜʙʟɪᴄ ᴄʜᴀɴɴᴇʟꜱ (ᴜꜱᴇ ᴛʜɪꜱ!):</b>\n<code>${migratorLink}</code>\n\n<blockquote><b>🔗 ᴀʟᴛᴇʀɴᴀᴛɪᴠᴇ ʟɪɴᴋꜱ:</b>\n<b>ᴄᴜʀʀᴇɴᴛ ʙᴏᴛ:</b> <code>${currentBotLink}</code></blockquote>\n\n<b>🆔 ᴍᴇꜱꜱᴀɢᴇ ɪᴅ:</b> <code>${postMsgId}</code>`;

    await ctx.api.editMessageText(msg.chat.id, replyMsg.message_id, responseText, {
      parse_mode: 'HTML',
      disable_web_page_preview: true,
      reply_markup: { inline_keyboard: [
        [{ text: 'ʀᴇᴅɪʀᴇᴄᴛ ʙᴏᴛ ʟɪɴᴋ', url: migratorLink }],
        [{ text: 'ᴄᴜʀʀᴇɴᴛ ʙᴏᴛ ʟɪɴᴋ', url: currentBotLink }],
      ]},
    });

    // Add button to DB channel post
    if (!ctx.settings.disable_btn) {
      try {
        await ctx.api.editMessageReplyMarkup(db, postMsgId, {
          inline_keyboard: [[{ text: '🚀 Get File', url: migratorLink }]],
        });
      } catch (e: any) {
        logger.warn('linkGen', `Could not add button to DB post: ${e.message}`);
      }
    }
  } catch (e: any) {
    await ctx.api.editMessageText(msg.chat.id, replyMsg.message_id,
      `❌ <b>Upload failed:</b> <code>${e.message}</code>`,
      { parse_mode: 'HTML' }
    );
  }
}
